### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by ecklm**
I have prepared a dockerfile for this project. If you install docker, and follow the instructions written in the head of the file, you can deploy this in a minute.

### CODE REVIEW

**Comment by ecklm** [comment]
The default is not to use any authentication token, but it can be overwriten in various ways even without modifying the Dockerfile.

**Comment by ecklm** [comment]
For now it is for discussion, some further improvements might still be necessary.
I get this error message when opening a chapter:

spectacle k26472

I'll figure it out shortly.

**Comment by ricardoduarte** [comment]
Hi @ecklm 
Good initiative. Bu I was thinking, Docker Hub has a Jupyter official image. It is better to use that image, isn't it?

**Comment by ecklm** [comment]
I tried base-notebook image like this: `docker run -it --rm -p 8888:8888 -v "$(pwd)":/home/jovyan/ jupyter/base-notebook`.

It seems to be good as it claims to support multi-user running, but there is two problems:
1. The error I previously sent is still present. It is that this notebook has been saved in a previous format. Maybe I will try it with a former jupyter version. However the better option would be to save them in v4 format. Can you do that @ricardoduarte?
2. The "official" container runs jupyter in python3. I may try to make it run on python2.

**Comment by ricardoduarte** [comment]
Great job @ecklm . I completely forgot about this "Python 2 situation".

I'll try to convert notebooks to version 4, but I don't have any time to do this at this moment. Actually these notebooks were created before Jupyter even exists, using iPython Notebook.

**Comment by ecklm** [comment]
I will make some more improvements, as there are still some issues with this. But then I will file a new pull request when they are fixed.

**Pull request merged**
